version: 2
jobs:
  build:
    working_directory: /home/tox/featuretools
    docker:
        - image: painless/tox
    steps:
      - checkout
      - run: pyenv local 2.7.13 3.5.2 3.6.0
      - run: make installdeps
      - run: make lint && gosu tox tox && codecov
