version: 2
jobs:
  build:
    working_directory: ~/featuretools
    docker:
        - image: themattrix/tox
    steps:
      - run: apt-update && apt-get install pandoc -y
      - checkout
      - run: pyenv local 2.7.15 3.5.6 3.6.6 3.7.0
      - run: make installdeps
      - run: make lint
      - run: make -C docs/ -e "SPHINXOPTS=-W" clean html
      - run: tox && codecov
